### 1. Create report (USER)
POST localhost:8080/api/v1/report
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMzNzg5NDcsImlkIjoxMSwiZW1haWwiOiJlc2htYXRAZ21haWwuY29tIiwiZXhwIjoxNjkzNDY1MzQ3LCJpc3MiOiJ5b3V0dWJlIGJ5IFNhbmphciJ9.y5sQbVMyg-rHSKQsdwxhkJtAmqHm__fCTdA4bFgyA4dHJ5LExi4vnVrbb70rHCoVrZAfN81a432OxA3FvqMw7g

{
  "content": "sexual content",
  "channelId": "d6ff6088-719f-4598-bd94-0bd9d3df5422"
}

###   2. ReportList Pagination ADMIN
GET localhost:8080/api/v1/report/pagination?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMzOTc2MDAsImlkIjo0LCJlbWFpbCI6InJ1bm5lcnBybzE5OTBAZ21haWwuY29tIiwiZXhwIjoxNjkzNDg0MDAwLCJpc3MiOiJ5b3V0dWJlIGJ5IFNhbmphciJ9.236Cc5JVJ6l0bPKGQ-6g2tBQLBejI_wBDjVBAcmYMxJ_m6tyjCpz9BGHx6YvbjjVJcjeeM0YayvU7iEighRiWg

###    3. Remove Report by id (ADMIN)
DELETE localhost:8080/api/v1/report/f4b3368b-76cf-44bd-a0bb-3b1dd43ba995
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMzOTc2MDAsImlkIjo0LCJlbWFpbCI6InJ1bm5lcnBybzE5OTBAZ21haWwuY29tIiwiZXhwIjoxNjkzNDg0MDAwLCJpc3MiOiJ5b3V0dWJlIGJ5IFNhbmphciJ9.236Cc5JVJ6l0bPKGQ-6g2tBQLBejI_wBDjVBAcmYMxJ_m6tyjCpz9BGHx6YvbjjVJcjeeM0YayvU7iEighRiWg

### 4. Report List By User id (ADMIN)
GET localhost:8080/api/v1/report/reportList/11
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMzOTc2MDAsImlkIjo0LCJlbWFpbCI6InJ1bm5lcnBybzE5OTBAZ21haWwuY29tIiwiZXhwIjoxNjkzNDg0MDAwLCJpc3MiOiJ5b3V0dWJlIGJ5IFNhbmphciJ9.236Cc5JVJ6l0bPKGQ-6g2tBQLBejI_wBDjVBAcmYMxJ_m6tyjCpz9BGHx6YvbjjVJcjeeM0YayvU7iEighRiWg

