insert into tag(id,name,visible,created_date)
values (uuid_generate_v4(),'tag test1',true,now());
insert into tag(id,name,visible,created_date)
values (uuid_generate_v4(),'tag test2',true,now());
insert into tag(id,name,visible,created_date)
values (uuid_generate_v4(),'tag test3',true,now());
insert into tag(id,name,visible,created_date)
values (uuid_generate_v4(),'tag test4',true,now());
insert into tag(id,name,visible,created_date)
values (uuid_generate_v4(),'tag test5',true,now());